name: amplitude_flutter
description: Official Flutter plugin for tracking events and revenue to Amplitude.
version: 1.4.0
homepage: https://github.com/amplitude/Amplitude-Flutter

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  crypto: "^2.0.6"
  device_info: "^0.4.1+4"
  http: "^0.12.0+2"
  package_info: ">=0.4.0+13 <2.0.0"
  path: "^1.6.4"
  shared_preferences: "^0.5.6+2"
  sqflite: "^1.1.5"
  uuid: "^2.0.1"
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "4.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.amplitude.amplitude_flutter
        pluginClass: AmplitudeFlutterPlugin
      ios:
        pluginClass: AmplitudeFlutterPlugin
